---
- name: Install TextToSpeech Requirements
  apt:
    name:
      #- libspeechd-dev'
      - flite
      - flite1-dev
      - libflite1
      - speech-dispatcher-flite
      - libasound2-dev
    state: present
  become: true
  
- name: Clone the Qt-Mustache repository
  git:
    repo: 'https://github.com/robertknight/qt-mustache.git'
    dest: "{{toolsdir}}/libraries/QtMustache"
    force: yes

- name: Clone the QxOrm repository
  git:
    repo: 'https://github.com/QxOrm/QxOrm.git'
    dest: "{{toolsdir}}/libraries/QxOrm"
    force: yes

- name: Clone the QtWaitingSpinner repository
  git:
    repo: 'https://github.com/snowwlex/QtWaitingSpinner.git'
    dest: "{{toolsdir}}/libraries/QtWaitingSpinner"
    force: yes
