---
- git_config:
    name: user.email
    repo: /etc
    scope: global
    value: '{{ git_user_email }}'

- git_config:
    name: user.name
    repo: /etc
    scope: global
    value: '{{ git_user_name }}'

- name: Configure Git credential storage
  command: "git config --global credential.helper store"

- name: Populate the Git credential store
  template:
    src: git_credentials.j2
    dest: "/home/{{user}}/.git-credentials"
    owner: "{{user}}"
    group: "{{user}}"
    mode: u=rw,g=,o=
  no_log: true

- name: Download the Git Prompt
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
    dest: /usr/local/bin/git-prompt.sh
    mode: 0777

- name: Source the Git Prompt
  lineinfile:
    path: /home/vagrant/.bashrc
    line: source /usr/local/bin/git-prompt.sh
    create: yes


