---
- name: Configure Git credential storage
    command: "git config --global credential.helper store"
- name: Populate the Git credential store
  template:
    src: git_credentials.j2
    dest: /home/{{user}}/.git-credentials
    owner: {{user}}
    group: {{user}}
    mode: u=rw,g=,o=
  no_log: true

