---
- import_tasks: git.yml
- import_tasks: bin_utils.yml
- import_tasks: kde-common.yml
- import_tasks: dependencies.yml

- import_tasks: mingw_64.yml
- import_tasks: installbuilder.yml

- import_tasks: qt-tools.yml
- import_tasks: qt.yml
- import_tasks: qt-mingw.yml
  when: use_mingw is defined and use_mingw == true
  
- import_tasks: qxorm.yml

- import_tasks: qt-android.yml
  when: use_android is defined and use_android == true
- import_tasks: qt-raspi.yml
  when: use_raspi is defined and use_raspi == true

- import_tasks: qt6.yml
  when: vs_qt_version_major is version( '6.0', '>=' )


