---
- name: Install MinGW 64
  apt:
    name: ['mingw-w64']
    state: present
  become: true

# Install MinGW Dependencies
- name: Install a DirectX header files from .deb package
  apt:
    deb: /vagrant/requirements/MinGW/MinGW-DirectX-dev.deb
  become: true

- name: Create Directory for MinGW QT Compilation
  file:
    path: "{{toolsdir}}/qt-{{ qt_version_full }}/mingw_64"
    state: directory
    mode: '0755'

- name: Copy Qt Cross-Compilation script
  template: src={{item}} dest=/usr/local/bin/vs-cross-compile-qt.sh mode=0755
  with_items:
    - vs-cross-compile-qt-with-qtspeech.sh
    #- vs-cross-compile-qt.sh
  become: true
  
# Wine is needed to get a list of all DLLs that need to be copied for deployment 
- name: Install Wine
  apt:
    name: ['wine-stable']
    state: present
  become: true
  when: install_wine
  
- name: Copy Vs-List-Dlls script
  template: src={{item}} dest=/usr/local/bin/ mode=0755
  with_items:
    - vs-list-dlls.sh
  become: true
  when: install_wine
