---
- name: Create directory for Qt MinGW_64
  file:
    path: "{{toolsdir}}/qt-{{vs_qt_version_full}}/mingw_64/"
    state: directory
    recurse: yes
    owner: "{{user}}"
    group: "{{user}}"
    
- name: Download and extract Qt MinGW_64
  unarchive:
    src: "http://downloads.vankosoft.org/distributions/0-qt-{{vs_qt_version_full}}-mingw_64.tbz2"
    dest: "{{toolsdir}}/qt-{{vs_qt_version_full}}/mingw_64/"
    remote_src: yes
  when: vs_qt_download
  
- name: Add Link to MinGW qmake
  file:
    src: "/home/vagrant/tools/qt-{{ vs_qt_version_full }}/mingw_64/bin/qmake"
    dest: "/usr/bin/qmake-mingw"
    state: link
  become: true
  when: vs_qt_download


