- name: Check if mysql driver exists for this qt version
  local_action: stat path="/vagrant/requirements/Qt/{{ qt_version_full }}/plugins/sqldrivers/libqsqlmysql.so"
  register: mysql_driver
  
- name: Add Qt Mysql Driver
  copy:
    src: "/vagrant/requirements/Qt/{{ qt_version_full }}/plugins/sqldrivers/libqsqlmysql.so"
    dest: "/home/vagrant/tools/qt-{{ qt_version_full }}/x86_64/plugins/sqldrivers/libqsqlmysql.so"
    owner: vagrant
    group: vagrant
    mode: '0755'
  when: mysql_driver.stat.exists

- name: Check if texttospeech plugin exists for this qt version
  local_action: stat path="/vagrant/requirements/Qt/{{ qt_version_full }}/plugins/texttospeech/libqttexttospeech_flite.so"
  register: texttospeech_plugin
  
- name: Ensures plugins/texttospeech dir exists
  file: path=/home/vagrant/tools/qt-{{ qt_version_full }}/x86_64/plugins/texttospeech state=directory
  
- name: Add Qt texttospeech plugin
  copy:
    src: "/vagrant/requirements/Qt/{{ qt_version_full }}/plugins/texttospeech/libqttexttospeech_flite.so"
    dest: "/home/vagrant/tools/qt-{{ qt_version_full }}/x86_64/plugins/texttospeech/libqttexttospeech_flite.so"
    owner: vagrant
    group: vagrant
    mode: '0755'
  when: texttospeech_plugin.stat.exists
