---
- name: Link Qmake to the Qt5
  file:
    src: "/home/vagrant/tools/qt-{{ qt_version_full }}/x86_64/bin/qmake"
    dest: "/usr/bin/qmake"
    state: link
  become: true

- name: Link QCollectionGenerator to the Qt5
  file:
    src: "/home/vagrant/tools/qt-{{ qt_version_full }}/x86_64/bin/qcollectiongenerator"
    dest: "/usr/bin/qcollectiongenerator"
    state: link
  become: true
  
- name: Link QHelpGenerator to the Qt5
  file:
    src: "/home/vagrant/tools/qt-{{ qt_version_full }}/x86_64/bin/qhelpgenerator"
    dest: "/usr/bin/qhelpgenerator"
    state: link
  become: true

- name: Install QT Dev Tools
  apt:
    name: ['qttools5-dev-tools']
    state: present
  become: true

- name: Publish UI Compiller For Ubuntu >= 18
  file:
    src: "/home/vagrant/tools/qt-{{ qt_version_full }}/x86_64/bin/uic"
    dest: "/usr/lib/qt5/bin/uic"
    state: link
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= '18'
  become: true

- name: Publish UI Compiller For Ubuntu < 18
  file:
    src: "/home/vagrant/tools/qt-{{ qt_version_full }}/x86_64/bin/uic"
    dest: "/usr/bin/uic"
    state: link
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version < '18'
  become: true

- name: Copy Qt Vs-compilation script
  template: src={{item}} dest=/usr/local/bin/ mode=0755
  with_items:
    - vs-compile-qt.sh
  become: true

- name: Install Needed Deployment Tools
  apt:
    name: ['patchelf']
    state: present
  become: true
  
- name: Download the AppImageTool
  get_url:
    url: https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
    dest: /usr/local/bin/appimagetool
    mode: 0755
  become: true
  
# Usage: vs-linuxdeployqt QVocabulary -unsupported-allow-new-glibc -exclude-libs="libqsqlpsql,libqsqlmysql" -bundle-non-qt-libs
#        vs-linuxdeployqt QVocabulary -unsupported-allow-new-glibc -exclude-libs="libqsqlpsql,libqsqlmysql" -bundle-non-qt-libs -appimage -always-overwrite
#        vs-linuxdeployqt QVocabulary -exclude-libs="libqsqlpsql,libqsqlmysql" -bundle-non-qt-libs
#
- name: Download the linuxdeployqt-7 AppImage
  get_url:
    url: https://github.com/probonopd/linuxdeployqt/releases/download/7/linuxdeployqt-7-x86_64.AppImage
    dest: /usr/local/bin/vs-linuxdeployqt
    mode: 0755
  become: true

