---
- name: Install aditional development packages for compiling Qt 5.15
  apt:
    name: ['libxcb-util-dev', 'libxcb-xinerama0-dev']
    state: present
  become: true

- name: Create directory for Qt X86_64
  file:
    path: "{{toolsdir}}/qt-{{vs_qt_version_full}}/x86_64/"
    state: directory
    recurse: yes
    owner: "{{user}}"
    group: "{{user}}"
  
- name: Download and extract Qt X86_64
  unarchive:
    src: "http://download.vankosoft.org/qt-{{vs_qt_version_full}}-x86_64.tbz2"
    dest: "{{toolsdir}}/qt-{{vs_qt_version_full}}/x86_64/"
    creates: "{{toolsdir}}/qt-{{vs_qt_version_full}}/x86_64/bin"
    remote_src: yes
  when: vs_qt_download

- name: Create directory for Qt MinGW_64
  file:
    path: "{{toolsdir}}/qt-{{vs_qt_version_full}}/mingw_64/"
    state: directory
    recurse: yes
    owner: "{{user}}"
    group: "{{user}}"
    
- name: Download and extract Qt MinGW_64
  unarchive:
    src: "http://download.vankosoft.org/qt-{{vs_qt_version_full}}-mingw_64.tbz2"
    dest: "{{toolsdir}}/qt-{{vs_qt_version_full}}/mingw_64/"
    creates: "{{toolsdir}}/qt-{{vs_qt_version_full}}/mingw_64/bin"
    remote_src: yes
  when: vs_qt_download

- name: Repair Links to the Qt5 Tools
  file:
    src: "/home/vagrant/tools/qt-{{ vs_qt_version_full }}/x86_64/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
  become: true
  loop:
     - qmake
     - uic
     - lupdate
     - lrelease
     - qcollectiongenerator
     - qhelpgenerator

