---
- name: Link Qmake to the Qt5
  file:
    src: "/home/vagrant/tools/qt-{{ qt_version_full }}/x86_64/bin/qmake"
    dest: "/usr/bin/qmake"
    state: link
  become: true

- name: Link QCollectionGenerator to the Qt5
  file:
    src: "/home/vagrant/tools/qt-{{ qt_version_full }}/x86_64/bin/qcollectiongenerator"
    dest: "/usr/bin/qcollectiongenerator"
    state: link
  become: true
  
- name: Link QHelpGenerator to the Qt5
  file:
    src: "/home/vagrant/tools/qt-{{ qt_version_full }}/x86_64/bin/qhelpgenerator"
    dest: "/usr/bin/qhelpgenerator"
    state: link
  become: true

- name: Install QT Dev Tools
  apt:
    name: ['qttools5-dev-tools']
    state: present
  become: true

- name: Publish UI Compiller
  file:
    src: "/home/vagrant/tools/qt-{{ qt_version_full }}/x86_64/bin/uic"
    dest: "/usr/lib/qt5/bin/uic"
    state: link
  become: true

- name: Copy Qt Vs-compilation script
  template: src={{item}} dest=/usr/local/bin/ mode=0755
  with_items:
    - vs-compile-qt.sh
  become: true


- name: Install Needed Deployment Tools
  apt:
    name: ['patchelf']
    state: present
  become: true
  
# Usage: vs-linuxdeployqt QVocabulary -unsupported-allow-new-glibc -exclude-libs="libqsqlpsql,libqsqlmysql"
- name: Download the linuxdeployqt-7 AppImage
  get_url:
    url: https://github.com/probonopd/linuxdeployqt/releases/download/7/linuxdeployqt-7-x86_64.AppImage
    dest: /usr/local/bin/vs-linuxdeployqt
    mode: 0755
  become: true

