---
# Get From: awinterstein/ansible-role-qt-dev
####################################################
- name: Clone the Qt source repository From Tag
  git:
    repo: "git://code.qt.io/qt/qt5.git"
    dest: "{{ toolsdir }}/qt5-src"
    version: "v{{ vs_qt_version_full }}"
    force: yes
  when: vs_qt_src_clone and not vs_qt_src_use_branch
  
- name: Clone the Qt source repository From Branch
  git:
    repo: "git://code.qt.io/qt/qt5.git"
    dest: "{{ toolsdir }}/qt5-src"
    version: "{{ vs_qt_version_full }}"
    force: yes
  when: vs_qt_src_clone and vs_qt_src_use_branch

- name: Install mesa development headers (for Qt gui development)
  apt:
    name: ["mesa-common-dev", "libgl1-mesa-dev"]
    state: present
  become: true
  
- name: Install development packages for compiling Qt
  apt:
    name:
      [
        "libfontconfig1-dev",
        "libfreetype6-dev",
        "libx11-dev",
        "libxext-dev",
        "libxfixes-dev",
        "libxi-dev",
        "libxrender-dev",
        "libxcb1-dev",
        "libx11-xcb-dev",
        "libxcb-glx0-dev",
        "libxkbcommon-x11-dev",
        "libxcb-keysyms1-dev",
        "libxcb-image0-dev",
        "libxcb-shm0-dev",
        "libxcb-icccm4-dev",
        "libxcb-sync0-dev",
        "libxcb-xfixes0-dev",
        "libxcb-shape0-dev",
        "libxcb-randr0-dev",
        "libxcb-render-util0-dev",
        "libssl-dev",
      ]
    state: present
  become: true

# My Own Artefacts
########################################################
- name: Install Aditional development packages for compiling Qt
  apt:
    name: "{{ aditional_development_packages }}"
    state: present
  become: true

- name: Create directory for Qt X86_64
  file:
    path: "{{toolsdir}}/qt-{{vs_qt_version_full}}/x86_64/"
    state: directory
    recurse: yes
    owner: "{{user}}"
    group: "{{user}}"
  
- name: Download and extract Qt X86_64
  unarchive:
    src: "http://downloads.vankosoft.org/distributions/0-qt-{{vs_qt_version_full}}-x86_64.tbz2"
    dest: "{{toolsdir}}/qt-{{vs_qt_version_full}}/x86_64/"
    remote_src: yes
  when: vs_qt_download

- name: Repair Links to the Qt Bin Tools
  file:
    src: "{{toolsdir}}/qt-{{ vs_qt_version_full }}/x86_64/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
  become: true
  loop: "{{ qt_bin_tools }}"
  when: vs_qt_download
  
- name: Repair Links to the Qt Libexec Tools
  file:
    src: "{{toolsdir}}/qt-{{ vs_qt_version_full }}/x86_64/libexec/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
  become: true
  loop: "{{ qt_libexec_tools }}"
  when: vs_qt_download

- name: Create Qt Build - Build Directory
  file:
    path: "{{toolsdir}}/qt-build/build"
    state: directory
    owner: "{{user}}"
    group: "{{user}}"
    
- name: Create Qt Build - Install Directory ( Prefix For The New Version Build)
  file:
    path: "{{toolsdir}}/qt-build/package"
    state: directory
    owner: "{{user}}"
    group: "{{user}}"

- name: Create Qt Build - Host Target Directory ( This Directory Needed For QT6 Cross Compilation )
  file:
    path: "{{toolsdir}}/qt-build/host-target"
    state: directory
    owner: "{{user}}"
    group: "{{user}}"

