---
# Install QxOrm Dev Dependencies
- name: Install a QxOrm from .deb package
  apt:
    deb: /vagrant/requirements/QxOrm/QxOrm-1.4.7.deb
  become: true

# Install QxEntityEditor - tar -xf archive.tar.gz -C /home/linuxize/files
- name: Install QxEntityEditor
  unarchive:
    src: /vagrant/requirements/QxOrm/QxEntityEditor_1.2.5_linux_64b.tar.gz
    dest: /opt
    remote_src: yes
  become: true
    
- name: Create Desktop Shortcuts
  template:
    src: "{{item}}"
    dest: /home/vagrant/Desktop/
    owner: vagrant
    group: vagrant
    mode: 0755
  with_items:
    - QxEntityEditor.desktop
  become: true
   
# MySql Support
- name: Install mysql development headers (for Qt mysql driver)
  apt:
    name: ['libmysqlclient-dev', 'libmysqlcppconn-dev']
    state: present
  become: true
